Use ActiveModel::Errors#import on Rails 6.1+
aaronmallen/activeinteractor pull request #299
Opened 2020-11-04 20:40 UTC by dark-panda

`ActiveModel::Errors#each` was changed in Rails 6.1.0 to iterate across an array of `ActiveModel::Error` objects instead of an array of values like `[attribute, message]`.

This PR begins the Rails 6.1 compatibility process, but it is not complete -- when the specs run, it currently hangs in an infinite loop part way through and uses 100% CPU while leaking memory until exhaustion. I haven't traced this particular issue yet, but wanted to get this PR up early to begin the work and avoid potential duplication of effort.

2020-11-05 21:56 UTC, aaronmallen requested changes
I know this is still draft, but I wanted to give some initial feedback.

2020-11-05 21:56 UTC, aaronmallen commented on lib/active_interactor/context/errors.rb
> -      def resolve_errors
this Module is set for deprecation and shouldn't actually be called anymore internally.  I don't think we need a fix here.

2020-11-05 21:56 UTC, aaronmallen commented on lib/active_interactor/interactor/result.rb
> +      if ActiveModel::Errors.method_defined?(:import)
I would rather see this split into two methods to ensure we don't inflate the complexity of `resolve_errors!`

2020-11-05 21:58 UTC, aaronmallen commented on lib/active_interactor/interactor/result.rb
> +      if ActiveModel::Errors.method_defined?(:import)
additionally we can call this in the method directly instead with `context.errors.respond_to?`

2020-11-05 22:15 UTC, aaronmallen commented on lib/active_interactor/interactor/result.rb
> +      if ActiveModel::Errors.method_defined?(:import)
```ruby
def resolve_errors!
  all_errors = context.errors.uniq.compact
  context.errors.clear
  merge_errors(all_errors)
end

def merge_errors(errors)
  errors.each do |error|
    if error.is_a?(ActiveModel::Error)
      context.errors.import(error)
    else
      context.errors.add(error[0], error[1])
    end
  end
end
```

2020-11-05 22:20 UTC, aaronmallen commented on lib/active_interactor/interactor/result.rb
> +      if ActiveModel::Errors.method_defined?(:import)
lastly it looks like we can possibly get rid of this logic all together by just calling `context.errors.uniq!`

2020-11-09 19:49 UTC, aaronmallen commented
@mohameddiaa27 since 1.1.x technically supports `'activemodel', '< 7.0'` I think we should also apply another patch there as well, WDYT?

2020-11-10 11:06 UTC, mohameddiaa27 commented
> @mohameddiaa27 since 1.1.x technically supports `'activemodel', '< 7.0'` I think we should also apply another patch there as well, WDYT?

Yes, makes sense 👍

2022-02-16 17:24 UTC, closed without merging