Fix rails dependencies for 6.1.x
aaronmallen/activeinteractor pull request #309
Opened 2021-01-11 16:06 UTC by dark-panda

## Description

The gem will install with Rails 6.1.0 but not Rails 6.1.1+ due to the dependency requirements.

## Changelog

### Changed

- Allow for Rails 6.1.x versions to be used.

2021-01-12 16:47 UTC, aaronmallen requested changes

2021-01-12 16:47 UTC, aaronmallen commented on activeinteractor.gemspec
> +  spec.add_dependency 'activesupport', '>= 4.2', '<= 6.1.99'
would rather do 

```ruby
spec.add_dependency 'activemodel', '>= 4.2', '< 6.2'
spec.add_dependency 'activesupport', '>= 4.2', '< 6.2'
```

2021-01-13 15:14 UTC, aaronmallen approved these changes

2021-10-21 08:38 UTC, yutakakanno commented
Excuse me.

Are there any plans to support Rails 6.1.x or later?

Currently, I'm planning to use it in the Rails project of 6.1.4, but I can't install it due to the dependency.

thank you.

2022-02-16 17:24 UTC, closed without merging